modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "speedcap"
version = "${version}"
displayName = "Speed Cap"
authors = "DialingSpoon"
description = '''
Cap your speed
'''
logoFile = "icon.png"

[[dependencies.speedcap]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.speedcap]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"