modLoader = "javafml"
loaderVersion = "[3,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "speedcap"
version = "${version}"
displayName = "Speed Cap"
authors = "DialingSpoon"
description = '''
Cap your speed
'''
logoFile = "icon.png"

[[mixins]]
config = "speedcap.mixins.json"
[[mixins]]
config = "speedcap.neoforge.mixins.json"

[[dependencies.speedcap]]
modId = "neoforge"
type = "required"
versionRange = "[21, 21.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.speedcap]]
modId = "minecraft"
type = "required"
versionRange = "[1.21, 1.21.3)"
ordering = "NONE"
side = "BOTH"